language: python
python:
- '3.6'
install:
- python3 -m pip install -r requirements.txt
script:
- python3 -m unittest discover -s tests
notifications:
  slack: conversinator:eCJM4feMnddtjb6cmnGIrZYn
env:
  global:
  - NEO_4J_URL=hobby-eceacfkfcpcngbkenilnegbl.dbs.graphenedb.com
  - NEO_4J_BOLT_PORT=24786
  - secure: SmfZul7kOwcsJVWJzQwivzrF65CqQWKPteJWlvmGSxqt7aw2dKBKLxwVntkcWVKgLIMo8orT2Xe3RXU4Rz1wqG7vVF678oT76XuIlUI9XZiELzCOWtcHdI7SSS+n1AvRLTJ6ngpkBlqyRkXJZUm5CXkF6o5FlOBNxhgpA2MpPFy139ZfG+auTYez8duXx+YGXsoWEv7evFzzk37uLpIOT/6jnev78Z+fKZbjNgtfPNyo1WWa9UID6qWiSuwyGR6qMZzSwiyIxXVyOLXKKF0nR1vB81O/Qaho7/FYkw9G8upfNRlfWeUTT+z+PttkXYYR5u41F9moQb31PJnm/A7a81Kr7Vyqol5HL0lEXVSNYJLig+dUnqvTzsiA00NW5JvoZx36pBRAvBIgOwF/NyamLZJaWtqoxDKMpnDQ0kJ0JF5TVHivR/CMLibUz+aAXqyw/o9/GwD1KRwDuCye1CYMCMmXrjQIEEex4V5VibqhRLJDM+Aq7akfyXKLByK6IeueSaJn+hfYN/NRmVVKvQ4RaQD77DyLkSZRUEGxOVujt6BRs0J5nJxrdjKBm0V8vr1uV8vTfUjmBLhdqGx/WZVACiYGhM4cnWgkUZ+zpZhSED1xLMCv8eSRzbv9O/QtcMLYjh9/bK/LOOIBpS8ZPhek6k0GRUzNQ9mbFWlAiMJuX1k=
  - secure: xiEQKL2O9zxSj23wHfTZEett+RxfNbdV204iN83fK85M7fXICYLD2kskhNst6APAfA82p0DxBiuuvRp0/4FqEwUy/x6q+Jyha7VNLeJ+3qdMpukrSaKUnwY534TxcGPmMXvZVrjMK2HU7IUY7dY2EC0IsJbGvV3pB7M9/xiIK/wfBVWXizqFKFapg4Su5tOFZCa7lFYWiI93I3zYZU2Y+KGiRJGcUh8W9r1FF+Za2R1Q78LJrAJqOh1fCq6eXyCKdu0u4f3J1EZW0hwoiY4h2zB9gdsIKxH55PMOHoYJEnE4ywlp95xjfFOAIcNT8G1YsUm8GV6aDczODLgAVwS7LE4D6E7pmI0hmbXmfKxujQVrbdGiKyWnXOlsUga+oO+jePh+3I1sir+fGxoj5OFNyXxpDG5qMOY0+pJa4I96l7NmH+V7cBifzC4F0lPmalIf+D9MdB84/6U3/nIgaPUcn2tqQuRbaYUm981aCnr5AInZL6NEYlfkR8CKtusJFR7HwfTApcepvUpzXA9ISBALk2owjU12LTbItM3Tids5lbK0jCQ0Pk/z3UP8tu1ymY+UH2xxRl0iyONgh4I4hJKxxdWEc6Fp08E2TddiPTDwaBbIPCul6mgKLD7JMu2a9fmQDnAesck8zr6SEFQhhG7dhQRT7oMkXRbhYASIT1Ii8gw=
