swagger: '2.0'
info:
title: FALSY SIMPLE DEMO API
version: "0.1"
consumes:
- application/json
produces:
- application/json
basePath: "/v1"
paths:
  '/hello':
    get:
      tags: [Method]
#      openerationId: demo.get_it
      summary: testing
      parameters:
      - name: name
        in: query
        type: string
        default: 'john'
      responses:
        200:
          description: Return response